Added test to check for alerts that are not enabled or does not have a notification
taddison/SQLChecks pull request #29
Opened 2019-01-18 19:50 UTC by andrewalumkal

2019-01-19 23:01 UTC, taddison commented
Thanks @andrewalumkal - could you:
- Add something to the docs that gives a brief description of the test
- Provide some details on how you think the exclusion works.  I'm wondering if you want to list the alerts you care about vs. add alerts you want to ignore.  Scenario I'm thinking about is testing 'at least 1 alert for ID XYZ exists', rather than has someone an alert.

2019-01-19 23:06 UTC, taddison requested changes

2019-01-19 23:06 UTC, taddison commented on src/SQLChecks/Functions/Public/Get-UnconfiguredAlerts.ps1
> +            Has_Notification = $_.has_notification
Could this be renamed


```suggestion
            HasNotification = $_.has_notification
```

2019-01-19 23:06 UTC, taddison commented on src/SQLChecks/Tests/SQLInstance.tests.ps1
> +Describe "SQL Alerts" -Tag SQLAlerts {
Could we pick a more descriptive tag - tags are globally unique in the module and drive config rules, so something that is verbose is better - maybe UnconfiguredSQLAgentAlerts ?

2019-01-19 23:06 UTC, taddison commented on src/SQLChecks/Tests/SQLInstance.tests.ps1
> +Describe "SQL Alerts" -Tag SQLAlerts {
Could we make this more descriptive - as it's unique on the module and frequently in config files with little context the more verbose the better.  UnconfiguredSQLAgentAlerts maybe?

2019-01-22 17:33 UTC, andrewalumkal commented on src/SQLChecks/Functions/Public/Get-UnconfiguredAlerts.ps1
> +            Has_Notification = $_.has_notification
Updated

2019-01-22 17:39 UTC, andrewalumkal commented
> Thanks @andrewalumkal - could you:
> 
> * Add something to the docs that gives a brief description of the test
> * Provide some details on how you think the exclusion works.  I'm wondering if you want to list the alerts you care about vs. add alerts you want to ignore.  Scenario I'm thinking about is testing 'at least 1 alert for ID XYZ exists', rather than has someone an alert.

Tim, so the check actually checks for ANY alert that is either disabled OR does not have an alert notification. The reason i picked this criteria is because if this was run against a new environment or after a migration, its good to know as an FYI what alerts are disabled OR which don't have a notification. 
The exclusion is to optionally exclude an alert we don't care about (report3 has log shipping alerts). The cleanest way to exclude would be to just delete the alert from SQL Server. But the exclusion is there in case you don't want to delete the alert, but keep it disabled / without a notification for some reason. Let me know if you would like to change the logic of this alert.

2019-01-22 17:41 UTC, taddison requested changes

2019-01-22 17:41 UTC, taddison commented on src/SQLChecks/Tests/SQLAgent.tests.ps1
> +Describe "Unconfigured SQL Agent Alerts" -Tag UnconfiguredSQLAgentAlerts {
This tag should match the documentation and function - `CheckUnconfiguredSQLAgentAlerts`

2019-01-23 20:50 UTC, taddison approved these changes

2019-01-23 20:52 UTC, merged

2019-01-23 20:52 UTC, taddison commented
Merged